- name: bree
  hosts: all
  become: yes


  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
    
    - name: drop the user flag
      copy:
        src: "barliman_flag.txt"
        dest: "/home/barliman/barliman_flag.txt"
        owner: barliman
        group: barliman

    - name: drop the root flag
      copy:
        src: "system_flag.txt"
        dest: "/root/system_flag.txt"
        owner: root
        group: root

    - name: run script
      ansible.builtin.script: DHCP_ASSIGN.sh
       
    - name: Clear Variable
      shell: unset IP_ADD
    
    - name: Fix Permissions for the Service
      shell: |
       chown -R www-data:www-data /var/www/html/cockpit/
       chmod -R 755 /var/www/html/cockpit/

    - name: Restart Apache
      shell: systemctl restart apache2

    - name: reboot the box to change hostname
      reboot:
    
   