- name: bree
  hosts: all
  become: yes

  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"

    - name: Make Privileged User
      user:
        name: "{{user_name}}"
        password: "{{user_hash}}"
        groups:
         - sudo
        state: present
    
    
    - name: drop the user flag
      copy:
        dest: "/home/{{user_name}}/barliman_flag.txt"
        content: |
          "{{user_flag}}"
        owner: "{{user_name}}"
        group: "{{user_name}}"


    - name: drop the root flag
      copy:
        dest: "/root/system_flag.txt"
        content: |
          "{{root_flag}}"
        owner: root
        group: root

    
    - name: Make the Compromised User
      user:
        name: "{{comp_user}}"
        password: "{{comp_hash}}"
        groups:
         - sudo
        state: present

    - name: Delete index.html
      shell: sudo rm /var/www/html/index.html

    #- name: copy cockpit directory
    #  shell: mv /home/deployer/cockpit /var/www/html

    - name: copy php.ini file
      copy:
        src: "configs/php.ini"
        dest: "/etc/php/7.4/apache2/php.ini"

    - name: Move the cockpit conf file
      copy:
        src: "configs/cockpit.conf"
        dest: "/etc/apache2/sites-available/cockpit.conf"
        
   # - name: Make the directory
   #   shell: |
   #     mkdir /var/www/html/cockpit/
        
    - name: Move cockpit files to box
      unarchive:
        src: "cockpit.tar"
        dest: "/var/www/html/"
        
    - name: Fix Permissions for the Service
      shell: |
       chown -R www-data:www-data /var/www/html/cockpit/
       chmod -R 755 /var/www/html/cockpit/
    
    - name: Enable Apache2 Service
      shell: systemctl enable apache2

    - name: Enable cockpit config
      shell: sudo a2ensite cockpit.conf

    - name: Enable Cockpit rewrite
      shell: sudo a2enmod rewrite

    - name: Restart Apache
      shell: systemctl restart apache2

    - name: reboot the box to change hostname
      reboot:
