- name: bree
  hosts: all
  become: yes

  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
    
    - name: drop the user flag
      copy:
        dest: "/home/{{user_name}}/barliman_flag.txt"
        owner: "{{user_name}}"
        group: "{{user_name}}"

    - name: drop the root flag
      copy:
        src: "system_flag.txt"
        dest: "/root/system_flag.txt"
        owner: root
        group: root
        
    - name: Delete index.html
      shell: sudo rm /var/www/html/index.html

    - name: copy cockpit directory
      shell: mv /home/deployer/cockpit /var/www/html
      
    - name: copy php.ini file
      copy:
        src: "files/php.ini"
        dest: "/etc/php/7.4/apache2/php.ini
      
    - name: Fix Permissions for the Service
      shell: |
       chown -R www-data:www-data /var/www/html/cockpit/
       chmod -R 755 /var/www/html/cockpit/

    - name: enable cockpit config
      shell: sudo a2enconf cockpit.conf

    - name: Enable Cockpit rewrite
      shell: sudo a2enmod rewrite

    - name: Restart Apache
      shell: systemctl restart apache2

    - name: reboot the box to change hostname
      reboot:
   
